# Language
FROM python:3.9-alpine

# Work Directory
WORKDIR /curriculo

# Put the content in the Work Directory
COPY . /curriculo

# Installing the dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Command that will run
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]